### PR TITLE
Fix python3 compatibility

### PR DESCRIPTION
**Pull request by Maxime2**
This PR addresses deprecation of distutils in python 3.10 and above.
It also improves python interpreter and flex version checks in configure.

And finally it fixes test configuration restoring tests execution (tested on Ubuntu 22.04). 
However the following test are still failing:
test_req_allow_methods, test_publisher_auth_nested, test_publisher_auth_method_nested
The first one fails due to [a bug in the recent Apache2](https://github.com/apache/httpd/pull/428); the later two are pending investigation.

### CODE REVIEW

**Comment by grisha** [comment]
Thanks for this @Maxime2! The python3 compatibility stuff is not something I know enough about.... What would be a good process to make sure that this can be merged?

**Comment by Maxime2** [comment]
Is there a list of OS we need to ensure it is buildable on?
I have checked it on Macbook Apple silicon with Sonoma MacOS and Apache2 installed using macports, - it is passing and failing the same tests as on Ubuntu 22.04/amd64.

**Comment by grisha** [comment]
Thanks, if it builds correctly on Ubuntu and OSX that's a good sign. It'd be nice if someone from the Centos/Fedora world could chime in. FreeBSD would be nice too.

I'll just leave this PR here for a little while so that other people if there are any could test this branch.

**Comment by grisha** [comment]
I've been able to verify that it builds on FreeBSD 31.2-RELEASE with httpd-2.4.59 and Python-3.11.9.

**Comment by grisha** [comment]
Okay I think it's okay to merge this at this point, big thanks to @Maxime2 for contributing the work!

**Pull request merged**
