### PR TITLE
(MODPYTHON-205) only check major and minor python version fields

### PR DESCRIPTION
**Pull request by jsoref**
(untested, I was hoping you had automation)

### CODE REVIEW

**Comment by jsoref** [comment]
So, this is based on lots of places reporting this problem:
1. https://issues.apache.org/jira/browse/MODPYTHON-205
1. https://bugs.launchpad.net/ubuntu/+source/libapache2-mod-python/+bug/1073147
1. https://bugzilla.redhat.com/show_bug.cgi?id=523051
1. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=592988
1. http://stackoverflow.com/questions/11454264/how-can-i-fix-python-version-mismatch-of-apache-mod-wsgi
1. http://serverfault.com/questions/445179/python-version-mismatch-expected-2-6-5-found-2-6-6
1. http://serverfault.com/questions/115415/python-init-python-version-mismatch-logged-in-apache-error-log

Afaict, from reading many of the reports, and from talking to python people, in general Python ABI should be pinned to Major.Minor, not Major.Minor.Patch+buildvariant.

This code change tries to applies that rule (* the `return -1` is probably wrong, and I haven't tested it -- my initial commit is more for discussion than merging).

Note that Mercurial uses Major.Minor and seems quite happy with it.

The system that I'm maintaining generates the following warning output:
```
[Wed Jan 04 18:50:35 2017] [error] python_init: Python version mismatch, expected '2.7.2+', found '2.7.9'.
[Wed Jan 04 18:50:35 2017] [error] python_init: Python executable found '/usr/bin/python'.
[Wed Jan 04 18:50:35 2017] [error] python_init: Python path being used '/usr/lib/python2.7/:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload'.
```

And it has the following debian packages installed:
```
ii  python                                         2.7.9-1                      amd64                        interactive high-level object-oriented language (default version)
ii  libapache2-mod-python                          3.3.1-9+b3                   amd64                        Python-embedding module for Apache 2
```

The rule for that module is:
```
Version: 3.3.1-9+b3
Replaces: libapache2-mod-python2.3 (<< 3.2.8-3), libapache2-mod-python2.4 (<< 3.2.8-3)
Provides: libapache2-mod-python2.7
Depends: python (<< 2.8), python (>= 2.7), python-central (>= 0.6.11), libc6 (>= 2.3), libpython2.7 (>= 2.7), libssl1.0.0 (>= 1.0.0), zlib1g (>= 1:1.1.4), apache2.2-common, apache2
```

Now, you could say "The debian maintainers got their rule wrong, it needs to be ==". And, you'd have to say the same thing to Red Hat, FreeBSD, and everyone else. But, they shouldn't need to do that, Python does have an ABI, and their (i.e. the debian maintainers') rules match that ABI (the module is pinned to python2.7* based on the first two items in Depends).

**Comment by grisha** [comment]
Thank you for the thorough explanation, I now understand it better, somehow I've never came across this. And I guess if mercurial does it, then no reason we couldn't either...

I don't really have a good way to test this though - if you have some time and can get it to a point where we have a slightly better assurance that this is good, it'd be great!

**Comment by jsoref** [comment]
So, this version should be easier to follow, it's much closer to the previous code.

The logic here is:
1. compiled version will be shifted to the right, and thus can not compare w/ `-1`.
1. start with dynamic value `-1`.
1. try to get `sys`.
1. if we can't get `sys`, skip to the end, leaving it as `-1`.
1. try to get `ver`.
1. drop `sys`.
1. if we didn't get `ver`, skip to the end, leaving it as `-1`.
1. `ver` is shifted to the right, and thus can be compared with the compiled version.
1. compare the compiled and dynamic versions.
1. if they don't compare as equal, complain as before.
1. use hex formatting to try to get a semblance of reasonable output for users.

**Comment by grisha** [comment]
@jsoref another thing I'm not sure about is whether it's possibly the Python API is used before the global interpreter is initialized below in the same function. I think the version is available as PY_VERSION_HEX without having to import sys and looking for hexversion in it, since this is where sys gets it from: https://github.com/python/cpython/blob/c0b23cf63f7570fc7a8bbe2d054d9484bb7d991e/Python/sysmodule.c#L1876-L1879 

I wonder if using PY_VERSION_HEX is a cleaner and simpler approach here?

**Comment by grisha** [comment]
Lol, nevermind the above comment, this was obviously typed up before I had my coffee :)

**Comment by grisha** [comment]
OK, so nevermind about the PY_VERSION_HEX above, but my concern regarding calling `PyImport_ImportModule("sys")` potentially before the `Py_Initialize()` still stands. I think at the very least we need a comment somewhere just before `sys = PyImport_ImportModule("sys");` explaining that it's okay to do this (assuming it actually is, of course), and why we're doing it.

And if it turns out that it's not okay to import sys before Py_Initialize, then I guess "plan B" could be just comparing the PY_VERSION string, a little messier, but should still work...

**Comment by jsoref** [comment]
https://docs.python.org/2/c-api/init.html

> void `Py_Initialize()`
> Initialize the Python interpreter. In an application embedding Python, this should be called before using any other Python/C API functions; with the exception of `Py_SetProgramName()`, `Py_SetPythonHome()`, `PyEval_InitThreads()`, `PyEval_ReleaseLock()`, and `PyEval_AcquireLock()`. This initializes the table of loaded modules (sys.modules), and creates the fundamental modules `__builtin__`, `__main__` and `sys`. It also initializes the module search path (sys.path). It does not set sys.argv; use `PySys_SetArgvEx()` for that. This is a no-op when called for a second time (without calling `Py_Finalize()` first). There is no return value; it is a fatal error if the initialization fails.

> const char* `Py_GetVersion()`
> Return the version of this Python interpreter. This is a string that looks something like
```
"1.5 (#67, Dec 31 1997, 22:34:28) [GCC 2.7.2.2]"
```
> The first word (up to the first space character) is the current Python version; the first three characters are the major and minor version separated by a period. The returned string points into static storage; the caller should not modify its value. The value is available to Python code as `sys.version`.

I see no provision indicating that what your code was doing (calling Py_GetVersion before Py_Initialize) was legal.

But I believe you're correct, the Py_Initialize should be moved before the code I'm inserting.

**Comment by grisha** [comment]
but you don't want to call `Py_Initialize()` if there is a version mismatch, so really you should check the version first, _then_ decided whether to proceed with Py_Initialize, you see the dilemma. 

Py_GetVersion was safe to call because its code doesn't really do much, as you can see here: https://github.com/python/cpython/blob/c30098c8c6014f3340a369a31df9c74bdbacc269/Python/getversion.c#L9-L15 But I don't think same can be said with respect to `PyImport_ImportModule()`.

**Comment by jsoref** [comment]
Sigh.

Ok. So, at this point, we need our own string parser.
Because the version really can be "3.2": https://github.com/python/cpython/commit/ed9c0dc3e6e78962ede7d8863756e5b9aa18faca

So, it's basically:
```c
bool ok = true;
int dots = 0;
for (char *sv = py_compile_version, *dv = py_dynamic_version; dots < 2; sv++, dv++) {
  char c = *sv;
  if (c != *dv) { ok = false; break; }
  if (c == '.' || c == ' ') dots++;
  else if (c == '\0') dots+=2;
}
```

And I'll have to find a compiler to talk to.

**Comment by grisha** [comment]
Another potentially simpler possibility is to compare _only up to the length of_ `PY_VERSION`, which I think in the above examples would be just `1.5` or `3.2`. The version returned from `Py_GetVersion` is a concatenation of PY_VERSION, Py_GetBuildInfo() and Py_GetCompiler(). But if we ignore everything past length of `PY_VERSION` we might have a win?

So basically something  like:
```
strncmp(py_compile_version, py_dynamic_version, strlen(py_compile_version)))
```

**Comment by jsoref** [comment]
No. Because PY_VERSION can be 1.5.4 and we don't want that .4 ...

**Comment by jsoref** [comment]
Note that what I have now isn't quite right either, since you're right, we're comparing "1.5\0" with "1.5.6 blah" -- we want them to compare equal.

**Pull request closed without merging**
