### PR TITLE
Fix compilation with python 3.7

### PR DESCRIPTION
**Pull request by wom-bat**
_PyImport_FixupExtensionObject now takes four arguments.
The libpython library is now 2-digit versioned (at least on Debian), so
use -lpython3.7 not -lpython3 at link time.
The StringField class subclasses bytes, which needs a str() as its
initialiser.
Py_GetPath() and Py_GetProgramFullPath() return wide-char strings,
so use %ls when printing.

### CODE REVIEW

**Comment by wom-bat** [comment]
This addresses issue #79

**Comment by grisha** [comment]
Thank you! Just a quick question on this - should it work for Python 3 versions older than 3.7?

**Comment by wom-bat** [comment]
Probably not.  _PyImport_FixupExtensionObject() now takes four arguments; it used to take three.  Python 3.6 or earlier use the 3-argument form.  The other changes should be benign.

**Comment by wom-bat** [comment]
I can add a guard around that if you like (but I don't really like #ifdefs in code.)

**Comment by grisha** [comment]
I think adding some ifdefs is the only way to go here so as to not break it for people with older Python.

**Comment by wom-bat** [comment]
I think the two changes I've just pushed will fix this.  The code builds cleanly against 2.7, 3,5 and 3.7; and I've tested 3.7.

**Pull request merged**
